import math
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp


def logic_and_language():
    print(f"\n{'='*50}")
    print(f"LOGIC AND LANGUAGE")
    print(f"{'='*50}")
    print(f"")
    print(f"  Before writing any proof, you need to understand")
    print(f"  the language mathematics is written in.")
    print(f"  Mathematical statements are built from simple pieces")
    print(f"  connected by logical rules.")
    print(f"  If you misread the statement, the proof goes nowhere.")
    print(f"")
    print(f"  1 — Propositions and connectives")
    print(f"  2 — Truth tables")
    print(f"  3 — Logical equivalences")
    print(f"  4 — Quantifiers  (for all, there exists)")
    print(f"")
    choice = input("  Enter 1, 2, 3, or 4: ")

    if choice == "1":
        propositions_and_connectives()
    elif choice == "2":
        truth_tables()
    elif choice == "3":
        logical_equivalences()
    elif choice == "4":
        quantifiers()
    else:
        print(f"  Invalid choice.")


def propositions_and_connectives():
    print(f"\n{'='*50}")
    print(f"PROPOSITIONS AND CONNECTIVES")
    print(f"{'='*50}")
    print(f"")
    print(f"  A proposition is a sentence that is either TRUE or FALSE.")
    print(f"  Not a question. Not an opinion. A precise claim.")
    print(f"")
    print(f"  Examples:")
    print(f"  · '2 + 2 = 4'       TRUE")
    print(f"  · '7 is even'        FALSE")
    print(f"  · 'It is raining'    TRUE or FALSE depending on reality")
    print(f"  · 'n is even'        depends on n — not a proposition by itself")
    print(f"                       it becomes one only when you fix n")
    print(f"")
    print(f"  Propositions can be combined with CONNECTIVES.")
    print(f"  These are the five words that build complex statements.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  NOT  (symbol: ¬)")
    print(f"  The opposite. ¬P is true exactly when P is false.")
    print(f"  'n is NOT even' = 'n is odd'")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  AND  (symbol: ∧)")
    print(f"  Both must be true. P ∧ Q is true only when P and Q are BOTH true.")
    print(f"  'n is even AND n > 10' — both conditions required.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  OR  (symbol: ∨)")
    print(f"  At least one is true. P ∨ Q is true when P, Q, or both hold.")
    print(f"  In mathematics, OR is always INCLUSIVE.")
    print(f"  'n is even OR n is odd' — always true for any integer.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  IF...THEN  (symbol: →)")
    print(f"  The most important connective in proofs.")
    print(f"  P → Q means: whenever P is true, Q must be true too.")
    print(f"  It is FALSE only in ONE case: P is true but Q is false.")
    print(f"  Think of it as a PROMISE: if P happens, Q is guaranteed.")
    print(f"  Breaking the promise (P true, Q false) is the only failure.")
    print(f"")
    print(f"  Example: 'If it is raining, I carry an umbrella.'")
    print(f"  · Raining + umbrella     = promise kept     TRUE")
    print(f"  · Raining + no umbrella  = promise broken   FALSE")
    print(f"  · Not raining + umbrella = I chose to bring it  TRUE")
    print(f"  · Not raining + no umbrella = fine           TRUE")
    print(f"")
    print(f"  The VACUOUS TRUTH: when P is false, P→Q is always true.")
    print(f"  'If 1=2 then I am a dinosaur' — technically true.")
    print(f"  Because P is false, the promise was never triggered.")
    print(f"  This surprises everyone at first. It is the correct definition.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  IF AND ONLY IF  (symbol: ↔)")
    print(f"  P ↔ Q means P and Q always have the same truth value.")
    print(f"  True when both true OR both false. Never one without the other.")
    print(f"  'n is even ↔ n² is even' — true for all integers.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  THE FOUR FORMS OF AN IMPLICATION P → Q:")
    print(f"")
    print(f"  Original:        P → Q      If P then Q")
    print(f"  Converse:        Q → P      If Q then P")
    print(f"  Contrapositive:  ¬Q → ¬P   If not Q then not P")
    print(f"  Inverse:         ¬P → ¬Q   If not P then not Q")
    print(f"")
    print(f"  CRUCIAL:")
    print(f"  P → Q and its CONTRAPOSITIVE ¬Q → ¬P are always equivalent.")
    print(f"  They say exactly the same thing, just phrased differently.")
    print(f"  This is why proving the contrapositive is a valid proof strategy.")
    print(f"")
    print(f"  The CONVERSE is NOT equivalent to the original.")
    print(f"  'If n=4 then n is even' is TRUE.")
    print(f"  'If n is even then n=4' is FALSE (n=2 is a counterexample).")
    print(f"  Confusing a statement with its converse is a very common error.")


def truth_tables():
    print(f"\n{'='*50}")
    print(f"TRUTH TABLES")
    print(f"{'='*50}")
    print(f"")
    print(f"  A truth table lists every possible combination of")
    print(f"  truth values and shows what the compound statement becomes.")
    print(f"  It is the most systematic way to check a logical claim.")
    print(f"")
    print(f"  With 2 variables P and Q, there are 4 combinations.")
    print(f"  With 3 variables, there are 8. With n variables, 2ⁿ.")
    print(f"")

    print(f"  NOT:")
    print(f"  {'P':>6}  {'¬P':>6}")
    print(f"  {'─'*15}")
    for p in [True, False]:
        print(f"  {'T' if p else 'F':>6}  {'T' if not p else 'F':>6}")

    print(f"")
    print(f"  AND — true only when BOTH are true:")
    print(f"  {'P':>6}  {'Q':>6}  {'P∧Q':>6}")
    print(f"  {'─'*22}")
    for p in [True, False]:
        for q in [True, False]:
            print(f"  {'T' if p else 'F':>6}  {'T' if q else 'F':>6}"
                  f"  {'T' if p and q else 'F':>6}")

    print(f"")
    print(f"  OR — true when AT LEAST ONE is true:")
    print(f"  {'P':>6}  {'Q':>6}  {'P∨Q':>6}")
    print(f"  {'─'*22}")
    for p in [True, False]:
        for q in [True, False]:
            print(f"  {'T' if p else 'F':>6}  {'T' if q else 'F':>6}"
                  f"  {'T' if p or q else 'F':>6}")

    print(f"")
    print(f"  IF-THEN — false ONLY when P is true and Q is false:")
    print(f"  {'P':>6}  {'Q':>6}  {'P→Q':>6}")
    print(f"  {'─'*22}")
    for p in [True, False]:
        for q in [True, False]:
            val = (not p) or q
            print(f"  {'T' if p else 'F':>6}  {'T' if q else 'F':>6}"
                  f"  {'T' if val else 'F':>6}")

    print(f"")
    print(f"  Look at row 2: P=T, Q=F, P→Q=F.")
    print(f"  That is the ONLY row where the implication fails.")
    print(f"  Every other combination makes P→Q true.")
    print(f"")
    print(f"  IFF — true when both agree:")
    print(f"  {'P':>6}  {'Q':>6}  {'P↔Q':>6}")
    print(f"  {'─'*22}")
    for p in [True, False]:
        for q in [True, False]:
            print(f"  {'T' if p else 'F':>6}  {'T' if q else 'F':>6}"
                  f"  {'T' if p==q else 'F':>6}")

    print(f"")
    print(f"  Now let's VERIFY that P→Q and ¬Q→¬P are identical:")
    print(f"  {'P':>4}  {'Q':>4}  {'P→Q':>6}  {'¬Q→¬P':>8}  {'Same?':>7}")
    print(f"  {'─'*34}")
    for p in [True, False]:
        for q in [True, False]:
            pq  = (not p) or q
            cpq = p or (not q)
            print(f"  {'T' if p else 'F':>4}  {'T' if q else 'F':>4}"
                  f"  {'T' if pq else 'F':>6}  {'T' if cpq else 'F':>8}"
                  f"  {'✓' if pq==cpq else '✗':>7}")
    print(f"")
    print(f"  Every row matches. P→Q and its contrapositive are always the same.")

    print(f"\n--- Build your own truth table ---")
    print(f"  Use: & for AND,  | for OR,  ~ for NOT,  > for →")
    print(f"  Variables: P, Q, R")
    print(f"  Example: (P & Q) | ~R")
    print(f"")
    formula = input("  Formula: ")

    print(f"\n  {'P':>4}  {'Q':>4}  {'R':>4}  Result")
    print(f"  {'─'*28}")
    for p in [True, False]:
        for q in [True, False]:
            for r in [True, False]:
                try:
                    expr = (formula
                            .replace("P", str(p))
                            .replace("Q", str(q))
                            .replace("R", str(r))
                            .replace("~", " not ")
                            .replace("&", " and ")
                            .replace("|", " or ")
                            .replace(">", " <= "))
                    result = eval(expr)
                    print(f"  {'T' if p else 'F':>4}  {'T' if q else 'F':>4}"
                          f"  {'T' if r else 'F':>4}  {'T' if result else 'F'}")
                except Exception:
                    print(f"  Could not evaluate — check the formula.")
                    break
            else:
                continue
            break


def logical_equivalences():
    print(f"\n{'='*50}")
    print(f"LOGICAL EQUIVALENCES")
    print(f"{'='*50}")
    print(f"")
    print(f"  Two statements are logically equivalent if they have")
    print(f"  the same truth value in every possible situation.")
    print(f"  We write P ≡ Q.")
    print(f"")
    print(f"  These are the algebra rules of logic.")
    print(f"  Just as 2(x+y) = 2x+2y in algebra,")
    print(f"  ¬(P∧Q) ≡ ¬P∨¬Q in logic.")
    print(f"  You use them to rewrite statements into easier forms.")
    print(f"")

    equivs = [
        ("Double negation",
         "¬¬P ≡ P",
         "Negating twice gives back the original.",
         "'Not not even' = 'even'. Always."),

        ("De Morgan's Law 1",
         "¬(P ∧ Q) ≡ ¬P ∨ ¬Q",
         "To negate AND, flip to OR and negate each part.",
         "'Not (raining AND cold)' = 'not raining OR not cold'."),

        ("De Morgan's Law 2",
         "¬(P ∨ Q) ≡ ¬P ∧ ¬Q",
         "To negate OR, flip to AND and negate each part.",
         "'Not (raining OR windy)' = 'not raining AND not windy'."),

        ("Contrapositive",
         "P → Q  ≡  ¬Q → ¬P",
         "An implication and its contrapositive say the same thing.",
         "Proved by the truth table above."),

        ("Implication as OR",
         "P → Q  ≡  ¬P ∨ Q",
         "Every IF-THEN can be rewritten as an OR.",
         "'If it rains I take umbrella' = 'It doesn't rain OR I have umbrella'."),

        ("Biconditional split",
         "P ↔ Q  ≡  (P → Q) ∧ (Q → P)",
         "IFF = both directions hold.",
         "To prove IFF, always prove both implications separately."),

        ("Distributivity",
         "P ∧ (Q ∨ R) ≡ (P∧Q) ∨ (P∧R)",
         "AND distributes over OR — just like × over + in algebra.",
         ""),
    ]

    for name, formula, meaning, example in equivs:
        print(f"  {'─'*46}")
        print(f"  {name}")
        print(f"  {formula}")
        print(f"  {meaning}")
        if example:
            print(f"  Example: {example}")
        print(f"")

    print(f"  {'─'*46}")
    print(f"  The three you will use constantly:")
    print(f"  · De Morgan — to negate complex statements")
    print(f"  · Contrapositive — to choose proof strategy")
    print(f"  · Biconditional split — for iff proofs")


def quantifiers():
    print(f"\n{'='*50}")
    print(f"QUANTIFIERS")
    print(f"{'='*50}")
    print(f"")
    print(f"  Most mathematical statements are about COLLECTIONS of objects.")
    print(f"  'For ALL integers n, ...'")
    print(f"  'There EXISTS a prime p such that ...'")
    print(f"  The words 'for all' and 'there exists' are QUANTIFIERS.")
    print(f"  They are everywhere in mathematics.")
    print(f"")
    print(f"  UNIVERSAL QUANTIFIER  ∀  ('for all', 'for every')")
    print(f"  ∀x P(x) means: P(x) is true for EVERY possible x.")
    print(f"")
    print(f"  To PROVE ∀x P(x):")
    print(f"  Take an ARBITRARY x — one with no special properties.")
    print(f"  Show P(x) holds. Since x was arbitrary, it holds for all x.")
    print(f"")
    print(f"  To DISPROVE ∀x P(x):")
    print(f"  Find ONE specific x where P(x) is false.")
    print(f"  This is called a COUNTEREXAMPLE.")
    print(f"  One counterexample is enough to destroy a 'for all' claim.")
    print(f"")
    print(f"  Example: ∀n∈ℤ, n² ≥ 0")
    print(f"  Proof: let n be any integer.")
    print(f"  If n≥0: n²=n·n≥0. If n<0: n²=(-n)·(-n)≥0. Done. □")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  EXISTENTIAL QUANTIFIER  ∃  ('there exists', 'there is')")
    print(f"  ∃x P(x) means: there is AT LEAST ONE x for which P(x) is true.")
    print(f"")
    print(f"  To PROVE ∃x P(x):")
    print(f"  Find ONE specific x that works and verify P(x).")
    print(f"  You don't need to find all solutions — just one.")
    print(f"")
    print(f"  To DISPROVE ∃x P(x):")
    print(f"  Show that P(x) is false for ALL x.")
    print(f"  (This is harder — you must prove a universal.)")
    print(f"")
    print(f"  Example: ∃n∈ℤ, n² = n")
    print(f"  Proof: take n=1. Then n²=1²=1=n. Done. □  (n=0 also works)")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  NEGATING QUANTIFIERS — De Morgan for quantifiers:")
    print(f"")
    print(f"  ¬(∀x P(x))  ≡  ∃x ¬P(x)")
    print(f"  'Not everyone passed' = 'Someone failed'")
    print(f"")
    print(f"  ¬(∃x P(x))  ≡  ∀x ¬P(x)")
    print(f"  'Nobody passed' = 'Everyone failed'")
    print(f"")
    print(f"  This rule is crucial. To negate a 'for all', write 'there exists not'.")
    print(f"  To negate a 'there exists', write 'for all not'.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  ORDER OF QUANTIFIERS MATTERS — a lot:")
    print(f"")
    print(f"  ∀x ∃y (y > x)")
    print(f"  'For every number, there exists a larger one.'")
    print(f"  TRUE — for any x, take y = x+1.")
    print(f"")
    print(f"  ∃y ∀x (y > x)")
    print(f"  'There is one number larger than ALL numbers.'")
    print(f"  FALSE — no largest number exists.")
    print(f"")
    print(f"  Same words, completely different meaning, just different order.")
    print(f"  Always read quantifiers from LEFT to RIGHT.")
    print(f"")
    print(f"  ─────────────────────────────────────────────")
    print(f"  UNIQUE EXISTENCE  ∃!")
    print(f"  ∃!x P(x) means: exactly ONE x satisfies P(x).")
    print(f"  To prove it, you need TWO things:")
    print(f"  1. EXISTENCE: find one x with P(x).")
    print(f"  2. UNIQUENESS: if P(x) and P(y), then x = y.")
    print(f"")
    print(f"  Example: ∃! real x such that x + 3 = 7")
    print(f"  Existence: x=4 works (4+3=7). ✓")
    print(f"  Uniqueness: if x+3=7 and y+3=7, then x=7-3=y. ✓")
    print(f"  Therefore there is exactly one solution. □")


def proof_structure():
    print(f"\n{'='*50}")
    print(f"ANALYZING PROOF STRUCTURE")
    print(f"{'='*50}")
    print(f"")
    print(f"  This is the heart of Velleman's approach.")
    print(f"  Most students try to prove things by staring at the problem")
    print(f"  and hoping an idea appears.")
    print(f"  Velleman's method is different and far more systematic:")
    print(f"  before writing a single word, analyze the STRUCTURE.")
    print(f"")
    print(f"  Every proof has two lists:")
    print(f"")
    print(f"  GIVENS                    GOAL")
    print(f"  ──────────────────────    ──────────────────────")
    print(f"  What you already know     What you need to show")
    print(f"  (the hypotheses)          (the conclusion)")
    print(f"")
    print(f"  A proof is a sequence of steps moving from givens to goal.")
    print(f"  Each step either ADDS something to the givens")
    print(f"  or TRANSFORMS the goal into something simpler.")
    print(f"")
    print(f"  The key insight: the FORM of the goal tells you")
    print(f"  exactly WHAT TO DO FIRST.")
    print(f"  You don't need to be clever — you need to read carefully.")
    print(f"")
    print(f"  1 — How to identify givens and goal")
    print(f"  2 — How the goal's form determines the strategy")
    print(f"  3 — Working forward vs working backward")
    print(f"  4 — Full example: analyzing a theorem from scratch")
    print(f"")
    choice = input("  Enter 1, 2, 3, or 4: ")

    if choice == "1":
        givens_and_goal()
    elif choice == "2":
        goal_form_strategy()
    elif choice == "3":
        forward_backward()
    elif choice == "4":
        analyze_theorem()
    else:
        print(f"  Invalid choice.")


def givens_and_goal():
    print(f"\n{'='*50}")
    print(f"GIVENS AND GOAL")
    print(f"{'='*50}")
    print(f"")
    print(f"  Every mathematical theorem has the form:")
    print(f"  'If [hypotheses], then [conclusion].'")
    print(f"  Even when it isn't written that way explicitly.")
    print(f"")
    print(f"  Before starting any proof, ask three questions:")
    print(f"  1. What am I GIVEN?   (write it down)")
    print(f"  2. What must I SHOW?  (write it down)")
    print(f"  3. What is the FORM of the goal?  (choose strategy)")
    print(f"")
    print(f"  Let's practice on four examples.")
    print(f"")

    examples = [
        {
            "theorem": "For all integers n, if n is odd then n² is odd.",
            "given":   ["n is an integer", "n is odd"],
            "goal":    "n² is odd",
            "form":    "universal (∀) + implication (→)",
            "strategy": "Introduce arbitrary n. Assume n is odd. Show n² is odd.",
            "note":    "The 'for all' means: pick any n — no special assumptions.\n"
                       "  The 'if...then' means: assume the hypothesis, prove the conclusion."
        },
        {
            "theorem": "There exists an integer n such that n² = n.",
            "given":   [],
            "goal":    "∃n∈ℤ: n² = n",
            "form":    "existential (∃)",
            "strategy": "Find one specific n that works and verify it.",
            "note":    "No hypotheses — just exhibit a witness.\n"
                       "  n=0: 0²=0 ✓  or  n=1: 1²=1 ✓  Either works."
        },
        {
            "theorem": "For all reals x, if x² = x then x=0 or x=1.",
            "given":   ["x is real", "x² = x"],
            "goal":    "x=0 or x=1",
            "form":    "universal + implication → disjunction (∨)",
            "strategy": "Assume x²=x. Show x=0 or x=1.",
            "note":    "The goal is a disjunction (OR).\n"
                       "  Strategy: assume the first option is false, prove the second.\n"
                       "  Or just solve the equation directly."
        },
        {
            "theorem": "For all integers m,n: m+n is even iff m,n have the same parity.",
            "given":   ["m, n are integers"],
            "goal":    "m+n even  ↔  (both even or both odd)",
            "form":    "universal + biconditional (↔)",
            "strategy": "Prove both directions: (→) and (←).",
            "note":    "IFF = two implications. Prove each one separately.\n"
                       "  (→): assume m+n even, show m,n same parity.\n"
                       "  (←): assume m,n same parity, show m+n even."
        },
    ]

    for i, ex in enumerate(examples):
        print(f"  {'─'*46}")
        print(f"  Example {i+1}:")
        print(f"  THEOREM: {ex['theorem']}")
        print(f"")
        print(f"  GIVEN:")
        if ex['given']:
            for g in ex['given']:
                print(f"    · {g}")
        else:
            print(f"    (no hypotheses)")
        print(f"")
        print(f"  GOAL:     {ex['goal']}")
        print(f"  FORM:     {ex['form']}")
        print(f"  STRATEGY: {ex['strategy']}")
        print(f"")
        print(f"  WHY:")
        for line in ex['note'].split('\n'):
            print(f"  {line}")
        print(f"")

    print(f"  {'─'*46}")
    print(f"  The habit to build:")
    print(f"  Every time you see a theorem, write GIVEN and GOAL.")
    print(f"  Don't start writing the proof until you've done this.")
    print(f"  The structure guides everything that follows.")


def goal_form_strategy():
    print(f"\n{'='*50}")
    print(f"GOAL FORM → PROOF STRATEGY")
    print(f"{'='*50}")
    print(f"")
    print(f"  This is Velleman's lookup table.")
    print(f"  Look at the form of your goal — it tells you the first move.")
    print(f"  Every time. No exceptions.")
    print(f"")

    strategies = [
        {
            "form":     "Goal: P ∧ Q  (AND)",
            "move":     "Split into two subgoals. Prove P, then prove Q.",
            "template": "(i)  Proof of P: ...\n"
                        "  (ii) Proof of Q: ...",
            "note":     "Both parts are required. Prove them independently."
        },
        {
            "form":     "Goal: P ∨ Q  (OR)",
            "move":     "Either prove P directly, or assume ¬P and prove Q.",
            "template": "Assume ¬P.\n"
                        "  [derive Q]\n"
                        "  Therefore Q, so P ∨ Q.",
            "note":     "If you know which is true, prove that one.\n"
                        "  If not, assume the opposite of one and derive the other."
        },
        {
            "form":     "Goal: P → Q  (IF-THEN)",
            "move":     "Assume P. Add it to givens. Prove Q.",
            "template": "Suppose P.\n"
                        "  [steps using P]\n"
                        "  Therefore Q.",
            "note":     "This is direct proof. Almost always try this first."
        },
        {
            "form":     "Goal: P ↔ Q  (IFF)",
            "move":     "Prove P→Q, then prove Q→P. Two separate proofs.",
            "template": "(→) Suppose P. [steps] Therefore Q.\n"
                        "  (←) Suppose Q. [steps] Therefore P.",
            "note":     "Never prove both directions in the same argument.\n"
                        "  Keep them clearly separated."
        },
        {
            "form":     "Goal: ∀x P(x)  (FOR ALL)",
            "move":     "Let x be an arbitrary element. Prove P(x).",
            "template": "Let x be arbitrary.\n"
                        "  [proof that P(x)]\n"
                        "  Since x was arbitrary, ∀x P(x). □",
            "note":     "Arbitrary means: no special assumptions about x.\n"
                        "  The proof must work for any x whatsoever."
        },
        {
            "form":     "Goal: ∃x P(x)  (THERE EXISTS)",
            "move":     "Exhibit a specific x₀. Verify P(x₀).",
            "template": "Let x₀ = [value].\n"
                        "  Then P(x₀): [verification]. □",
            "note":     "Finding x₀ requires insight. Verifying it is mechanical.\n"
                        "  Do the scratch work first: solve P(x) for x."
        },
        {
            "form":     "Goal: ¬P  (NEGATION)",
            "move":     "Assume P and derive a contradiction.",
            "template": "Suppose for contradiction that P.\n"
                        "  [steps leading to contradiction]\n"
                        "  Contradiction. Therefore ¬P. □",
            "note":     "Use when direct proof seems impossible.\n"
                        "  Best for proving non-existence or irrationality."
        },
    ]

    for s in strategies:
        print(f"  {'─'*46}")
        print(f"  IF THE GOAL IS: {s['form']}")
        print(f"  FIRST MOVE: {s['move']}")
        print(f"")
        print(f"  Template:")
        for line in s['template'].split('\n'):
            print(f"    {line}")
        print(f"")
        print(f"  Note: {s['note']}")
        print(f"")

    print(f"  {'─'*46}")
    print(f"  How to use this table:")
    print(f"  1. Look at your goal's form.")
    print(f"  2. Apply the first move.")
    print(f"  3. Look at the NEW goal's form.")
    print(f"  4. Apply the next move.")
    print(f"  5. Repeat until done.")
    print(f"  The process is mechanical once you know the table.")


def forward_backward():
    print(f"\n{'='*50}")
    print(f"WORKING FORWARD AND BACKWARD")
    print(f"{'='*50}")
    print(f"")
    print(f"  In a proof you can reason in two directions:")
    print(f"")
    print(f"  FORWARD — from the givens:")
    print(f"  'From P, I can derive...'")
    print(f"  'From that, I can derive...'")
    print(f"  Keep going until you reach the goal.")
    print(f"")
    print(f"  BACKWARD — from the goal:")
    print(f"  'To prove Q, it would be enough to show...'")
    print(f"  'To show that, it suffices to prove...'")
    print(f"  Keep going until you reach something you know.")
    print(f"")
    print(f"  In practice: work BOTH directions in your scratch work.")
    print(f"  From the givens: what can I derive?")
    print(f"  From the goal: what would be enough?")
    print(f"  Meet in the middle.")
    print(f"")
    print(f"  IMPORTANT RULE:")
    print(f"  In the FINAL WRITTEN PROOF, always go FORWARD.")
    print(f"  Start from the givens, end at the goal.")
    print(f"  Never write 'it suffices to show' in a clean final proof.")
    print(f"  The backward reasoning was your scratch work — don't show it.")
    print(f"")
    print(f"  --- A COMPLETE EXAMPLE ---")
    print(f"")
    print(f"  Theorem: if n² is even, then n is even.")
    print(f"")
    print(f"  SCRATCH WORK (backward):")
    print(f"  Goal: n is even.")
    print(f"  This means n = 2k for some integer k.")
    print(f"  Can I show n = 2k from 'n² is even'? Hard.")
    print(f"  Let me try the contrapositive instead.")
    print(f"")
    print(f"  SCRATCH WORK (try contrapositive):")
    print(f"  Original:        n² even → n even")
    print(f"  Contrapositive:  n odd   → n² odd")
    print(f"  Given: n = 2k+1. Show: n² = 2m+1.")
    print(f"  n² = (2k+1)² = 4k²+4k+1 = 2(2k²+2k)+1. Done!")
    print(f"")
    print(f"  FINAL PROOF (written forward):")
    print(f"  We prove the contrapositive: if n is odd, then n² is odd.")
    print(f"  Suppose n is odd. Then n = 2k+1 for some integer k.")
    print(f"  Therefore n² = (2k+1)² = 4k²+4k+1 = 2(2k²+2k)+1.")
    print(f"  Since 2k²+2k is an integer, n² is odd.")
    print(f"  By contrapositive, n² even implies n even. □")
    print(f"")
    print(f"  The scratch work was messy. The final proof is 4 lines.")
    print(f"  That's normal. Proofs are cleaned up, not first drafts.")


def analyze_theorem():
    print(f"\n{'='*50}")
    print(f"FULL EXAMPLE: ANALYZING A THEOREM FROM SCRATCH")
    print(f"{'='*50}")
    print(f"")
    print(f"  Let's go through the complete analysis process.")
    print(f"")
    print(f"  THEOREM:")
    print(f"  For all integers a, b, c:")
    print(f"  if a divides b and a divides c, then a divides (b+c).")
    print(f"  (where 'a divides b' means b = a·k for some integer k)")
    print(f"")
    print(f"  STEP 1: Write down GIVEN and GOAL.")
    print(f"")
    print(f"  GIVEN:")
    print(f"  · a, b, c are integers")
    print(f"  · a | b  (a divides b)")
    print(f"  · a | c  (a divides c)")
    print(f"")
    print(f"  GOAL: a | (b+c)")
    print(f"")
    print(f"  STEP 2: Unpack the definitions.")
    print(f"  Always translate symbols into what they actually mean.")
    print(f"")
    print(f"  'a | b' means: ∃j∈ℤ such that b = a·j")
    print(f"  'a | c' means: ∃k∈ℤ such that c = a·k")
    print(f"  'a | (b+c)' means: ∃m∈ℤ such that b+c = a·m")
    print(f"")
    print(f"  STEP 3: Look at the goal form.")
    print(f"  Goal: ∃m∈ℤ: b+c = a·m")
    print(f"  Form: existential (∃)")
    print(f"  Strategy: find the specific m.")
    print(f"")
    print(f"  STEP 4: Scratch work — find m.")
    print(f"  From the givens: b = a·j and c = a·k")
    print(f"  So b+c = a·j + a·k = a·(j+k)")
    print(f"  The m we need is m = j+k.")
    print(f"  Since j,k are integers, j+k is an integer. ✓")
    print(f"")
    print(f"  STEP 5: Write the clean proof.")
    print(f"")
    print(f"  ┌─────────────────────────────────────────┐")
    print(f"  │ Let a, b, c be arbitrary integers.      │")
    print(f"  │ Suppose a | b and a | c.                │")
    print(f"  │ Then b = aj and c = ak for some j,k∈ℤ. │")
    print(f"  │ Therefore b+c = aj+ak = a(j+k).         │")
    print(f"  │ Since j+k is an integer, a | (b+c). □   │")
    print(f"  └─────────────────────────────────────────┘")
    print(f"")
    print(f"  Five lines. That's it.")
    print(f"  The analysis took much longer than the writing.")
    print(f"  This is always true for well-written proofs.")
    print(f"")
    print(f"  WHAT MADE THIS WORK:")
    print(f"  · We unpacked every definition immediately")
    print(f"  · We identified the goal form (existential)")
    print(f"  · We did scratch work to find m before writing the proof")
    print(f"  · Every given was used exactly once")
    print(f"  · The final proof goes cleanly forward")


def proof_techniques():
    print(f"\n{'='*50}")
    print(f"PROOF TECHNIQUES")
    print(f"{'='*50}")
    print(f"")
    print(f"  Each technique handles a specific type of goal.")
    print(f"  Once you recognize the form, the technique is automatic.")
    print(f"")
    print(f"  1  — Direct proof")
    print(f"  2  — Proof by contrapositive")
    print(f"  3  — Proof by contradiction")
    print(f"  4  — Proof by cases")
    print(f"  5  — Proving AND statements")
    print(f"  6  — Proving OR statements")
    print(f"  7  — Proving IFF statements")
    print(f"  8  — Proving FOR ALL statements")
    print(f"  9  — Proving THERE EXISTS statements")
    print(f"  10 — Proof by induction")
    print(f"  11 — Strong induction")
    print(f"")
    choice = input("  Enter 1-11: ")

    if choice == "1":
        direct_proof()
    elif choice == "2":
        contrapositive_proof()
    elif choice == "3":
        contradiction_proof()
    elif choice == "4":
        proof_by_cases()
    elif choice == "5":
        proving_conjunctions()
    elif choice == "6":
        proving_disjunctions()
    elif choice == "7":
        proving_biconditionals()
    elif choice == "8":
        proving_universals()
    elif choice == "9":
        proving_existentials()
    elif choice == "10":
        proof_by_induction()
    elif choice == "11":
        strong_induction()
    else:
        print(f"  Invalid choice.")


def direct_proof():
    print(f"\n{'='*50}")
    print(f"DIRECT PROOF")
    print(f"{'='*50}")
    print(f"")
    print(f"  The most natural strategy.")
    print(f"  Goal: P → Q")
    print(f"  Method: assume P is true, then derive Q step by step.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Suppose P.                           │")
    print(f"  │ [steps]                              │")
    print(f"  │ Therefore Q. □                       │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  When to use it: almost always try this first.")
    print(f"  If the hypothesis gives you something concrete,")
    print(f"  you can usually work forward to the conclusion.")
    print(f"")
    print(f"  --- EXAMPLE 1 ---")
    print(f"  Theorem: if n is even, then n² is even.")
    print(f"")
    print(f"  ANALYSIS:")
    print(f"  Given: n is even → n = 2k for some integer k")
    print(f"  Goal:  n² is even → n² = 2m for some integer m")
    print(f"  Find m: n² = (2k)² = 4k² = 2(2k²)")
    print(f"  So m = 2k².")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose n is even.")
    print(f"  Then n = 2k for some integer k.")
    print(f"  Therefore n² = (2k)² = 4k² = 2(2k²).")
    print(f"  Since 2k² is an integer, n² is even. □")
    print(f"")
    print(f"  --- EXAMPLE 2 ---")
    print(f"  Theorem: if a | b and b | a, then a = b or a = -b.")
    print(f"")
    print(f"  ANALYSIS:")
    print(f"  a | b means b = ak for some integer k")
    print(f"  b | a means a = bm for some integer m")
    print(f"  Substitute: a = (ak)m = a(km)")
    print(f"  If a ≠ 0: km = 1, so k=m=1 or k=m=-1")
    print(f"  k=1 gives b=a; k=-1 gives b=-a.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose a | b and b | a.")
    print(f"  Then b = ak and a = bm for some integers k, m.")
    print(f"  If a = 0: b = 0·k = 0 = a, so a = b. ✓")
    print(f"  If a ≠ 0: substituting, a = (ak)m = a(km).")
    print(f"  Dividing by a: km = 1.")
    print(f"  Since k and m are integers: k = m = 1 or k = m = -1.")
    print(f"  If k=1: b = a·1 = a.")
    print(f"  If k=-1: b = a·(-1) = -a.")
    print(f"  Therefore a = b or a = -b. □")


def contrapositive_proof():
    print(f"\n{'='*50}")
    print(f"PROOF BY CONTRAPOSITIVE")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: P → Q")
    print(f"  Equivalent goal: ¬Q → ¬P  (contrapositive)")
    print(f"  Method: assume ¬Q is true, derive ¬P.")
    print(f"")
    print(f"  This is still a direct proof — just of the contrapositive.")
    print(f"  It is NOT the same as proof by contradiction.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ We prove the contrapositive.         │")
    print(f"  │ Suppose ¬Q.                          │")
    print(f"  │ [steps]                              │")
    print(f"  │ Therefore ¬P. □                      │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  When to use it:")
    print(f"  · When assuming ¬Q gives more to work with than assuming P.")
    print(f"  · When the conclusion is a negation (easier to produce ¬P directly).")
    print(f"  · When direct proof feels stuck.")
    print(f"")
    print(f"  --- EXAMPLE 1 ---")
    print(f"  Theorem: if n² is odd, then n is odd.")
    print(f"")
    print(f"  Direct is hard: 'n² is odd' is awkward to use.")
    print(f"  Contrapositive: 'n is even → n² is even' — easy!")
    print(f"")
    print(f"  PROOF:")
    print(f"  We prove the contrapositive: if n is even, then n² is even.")
    print(f"  Suppose n is even. Then n = 2k for some integer k.")
    print(f"  Therefore n² = (2k)² = 4k² = 2(2k²).")
    print(f"  Since 2k² is an integer, n² is even. □")
    print(f"")
    print(f"  --- EXAMPLE 2 ---")
    print(f"  Theorem: for all reals x, if x²+x < 0 then x < 0.")
    print(f"")
    print(f"  Contrapositive: if x ≥ 0 then x²+x ≥ 0.")
    print(f"  Assuming x ≥ 0 gives x² ≥ 0 immediately — perfect.")
    print(f"")
    print(f"  PROOF:")
    print(f"  We prove the contrapositive: if x ≥ 0 then x²+x ≥ 0.")
    print(f"  Suppose x ≥ 0.")
    print(f"  Then x² ≥ 0 (square of any real number) and x ≥ 0.")
    print(f"  Therefore x²+x = x²+x ≥ 0+0 = 0. □")
    print(f"")
    print(f"  NOTICE:")
    print(f"  Contrapositive ≠ Contradiction.")
    print(f"  Contrapositive: assume ¬Q, derive ¬P. Clean and direct.")
    print(f"  Contradiction: assume ¬P AND Q, derive something impossible.")
    print(f"  They're different techniques. Don't confuse them.")


def contradiction_proof():
    print(f"\n{'='*50}")
    print(f"PROOF BY CONTRADICTION")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: prove P is true.")
    print(f"  Method: assume ¬P. Derive something that is IMPOSSIBLE.")
    print(f"  Since ¬P leads to a contradiction, ¬P must be false.")
    print(f"  Therefore P is true.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Suppose for contradiction that ¬P.   │")
    print(f"  │ [steps]                              │")
    print(f"  │ But this contradicts [something].    │")
    print(f"  │ Therefore P. □                       │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  A WARNING:")
    print(f"  This technique is often OVERUSED by beginners.")
    print(f"  Many students write 'suppose for contradiction'")
    print(f"  and then give what is actually a contrapositive proof.")
    print(f"  If your 'contradiction' is just ¬Q → ¬P,")
    print(f"  write it as contrapositive — it's cleaner and clearer.")
    print(f"")
    print(f"  Best uses of contradiction:")
    print(f"  · Proving something does NOT exist")
    print(f"  · Proving irrationality")
    print(f"  · Proving infinitely many of something")
    print(f"")
    print(f"  --- EXAMPLE 1: √2 is irrational ---")
    print(f"")
    print(f"  ANALYSIS:")
    print(f"  Goal: √2 ∉ ℚ (not rational)")
    print(f"  Assume ¬goal: √2 = p/q in lowest terms (gcd(p,q)=1)")
    print(f"  Square: 2 = p²/q² → p² = 2q² → p even → p=2k")
    print(f"  → q² = 2k² → q even → both p,q even → contradicts gcd=1")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose for contradiction that √2 is rational.")
    print(f"  Then √2 = p/q where p,q∈ℤ, q≠0, and gcd(p,q)=1.")
    print(f"  Squaring: 2 = p²/q², so p² = 2q².")
    print(f"  Therefore p² is even, so p is even (proved earlier).")
    print(f"  Write p = 2k. Then 4k² = 2q², so q² = 2k².")
    print(f"  Therefore q² is even, so q is even.")
    print(f"  But then 2 | p and 2 | q, contradicting gcd(p,q) = 1.")
    print(f"  Therefore √2 is irrational. □")
    print(f"")
    print(f"  --- EXAMPLE 2: infinitely many primes ---")
    print(f"")
    print(f"  ANALYSIS:")
    print(f"  Assume finitely many primes: p₁, p₂, ..., pₙ.")
    print(f"  Build N = p₁·p₂·...·pₙ + 1.")
    print(f"  N has a prime factor p — which must be one of p₁,...,pₙ.")
    print(f"  But p divides both N and p₁·...·pₙ, so p divides 1.")
    print(f"  No prime divides 1 — contradiction.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose for contradiction there are finitely many primes.")
    print(f"  List them: p₁, p₂, ..., pₙ.")
    print(f"  Let N = p₁·p₂·...·pₙ + 1.")
    print(f"  Since N > 1, N has a prime factor p = pᵢ for some i.")
    print(f"  Then pᵢ | N and pᵢ | p₁·...·pₙ.")
    print(f"  So pᵢ | (N - p₁·...·pₙ) = 1.")
    print(f"  But no prime divides 1 — contradiction.")
    print(f"  Therefore there are infinitely many primes. □")


def proof_by_cases():
    print(f"\n{'='*50}")
    print(f"PROOF BY CASES")
    print(f"{'='*50}")
    print(f"")
    print(f"  Sometimes a situation naturally breaks into several scenarios.")
    print(f"  Proof by cases handles each scenario with its own argument.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ We consider [n] cases.               │")
    print(f"  │ Case 1: [condition].                 │")
    print(f"  │   [proof for case 1]                 │")
    print(f"  │ Case 2: [condition].                 │")
    print(f"  │   [proof for case 2]                 │")
    print(f"  │ In all cases, [conclusion]. □        │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  The cases must be EXHAUSTIVE — they must cover everything.")
    print(f"  They don't need to be mutually exclusive,")
    print(f"  but each case must be proved on its own.")
    print(f"")
    print(f"  Common case splits:")
    print(f"  · n even / n odd")
    print(f"  · x > 0 / x = 0 / x < 0")
    print(f"  · n ≡ 0 / n ≡ 1 / n ≡ 2  (mod 3)")
    print(f"")
    print(f"  --- EXAMPLE 1 ---")
    print(f"  Theorem: for all integers n, n² + n is even.")
    print(f"")
    print(f"  Cases: n even or n odd.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Let n be an arbitrary integer.")
    print(f"  Case 1: n is even. Then n = 2k for some k.")
    print(f"    n²+n = 4k²+2k = 2(2k²+k). Even. ✓")
    print(f"  Case 2: n is odd. Then n = 2k+1 for some k.")
    print(f"    n²+n = (2k+1)²+(2k+1) = 4k²+4k+1+2k+1")
    print(f"         = 4k²+6k+2 = 2(2k²+3k+1). Even. ✓")
    print(f"  In both cases n²+n is even. □")
    print(f"")
    print(f"  --- EXAMPLE 2 ---")
    print(f"  Theorem: for all reals x, |x| ≥ 0.")
    print(f"")
    print(f"  Cases: x ≥ 0 or x < 0.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Let x be an arbitrary real number.")
    print(f"  Case 1: x ≥ 0. Then |x| = x ≥ 0. ✓")
    print(f"  Case 2: x < 0. Then |x| = -x > 0. ✓")
    print(f"  In both cases |x| ≥ 0. □")


def proving_conjunctions():
    print(f"\n{'='*50}")
    print(f"PROVING AND STATEMENTS  (P ∧ Q)")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: P ∧ Q  (both P and Q)")
    print(f"  Method: prove P, then prove Q. Both must be shown.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ We show two things:                  │")
    print(f"  │ (i)  P: [proof]                      │")
    print(f"  │ (ii) Q: [proof]                      │")
    print(f"  │ Therefore P ∧ Q. □                   │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  Being explicit about (i) and (ii) makes the structure clear.")
    print(f"  The reader sees exactly what you're proving at each stage.")
    print(f"")
    print(f"  Example:")
    print(f"  Theorem: if 6 | n, then 2 | n AND 3 | n.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose 6 | n. Then n = 6k for some integer k.")
    print(f"  (i)  2 | n: n = 6k = 2(3k). Since 3k∈ℤ, 2 | n. ✓")
    print(f"  (ii) 3 | n: n = 6k = 3(2k). Since 2k∈ℤ, 3 | n. ✓")
    print(f"  Therefore 2 | n and 3 | n. □")
    print(f"")
    print(f"  Notice: both parts used the same given (n=6k)")
    print(f"  but produced independent conclusions.")
    print(f"  Always prove each part separately — don't mix them.")


def proving_disjunctions():
    print(f"\n{'='*50}")
    print(f"PROVING OR STATEMENTS  (P ∨ Q)")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: P ∨ Q  (P or Q or both)")
    print(f"")
    print(f"  METHOD 1 — if you know which is true:")
    print(f"  Prove that one directly.")
    print(f"  'Since [reason], P holds. Therefore P ∨ Q.'")
    print(f"")
    print(f"  METHOD 2 — if you don't know which:")
    print(f"  Assume ¬P. Use it to prove Q.")
    print(f"  This works because P ∨ Q ≡ ¬P → Q.")
    print(f"")
    print(f"  Template (method 2):")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Suppose ¬P.                          │")
    print(f"  │ [derive Q from ¬P and givens]        │")
    print(f"  │ Therefore P ∨ Q. □                   │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  Example:")
    print(f"  Theorem: for all reals x, x² ≥ 0 or x < 0.")
    print(f"  (Actually x² ≥ 0 always — so method 1 works here.)")
    print(f"")
    print(f"  PROOF (method 1):")
    print(f"  Let x be any real. Then x² = x·x ≥ 0 always.")
    print(f"  Therefore x² ≥ 0, so x² ≥ 0 OR x < 0. □")
    print(f"")
    print(f"  Example using method 2:")
    print(f"  Theorem: if n² is even then n is even or n = 0.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Suppose n² is even. Assume n ≠ 0.")
    print(f"  Since n² is even, n is even (by earlier theorem).")
    print(f"  Therefore n is even OR n = 0. □")


def proving_biconditionals():
    print(f"\n{'='*50}")
    print(f"PROVING IFF STATEMENTS  (P ↔ Q)")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: P ↔ Q")
    print(f"  Method: prove BOTH directions — two separate proofs.")
    print(f"  P ↔ Q means (P → Q) AND (Q → P).")
    print(f"  You cannot prove both at once. Always separate them.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ (→) Suppose P. [steps] Therefore Q. │")
    print(f"  │ (←) Suppose Q. [steps] Therefore P. │")
    print(f"  │ Therefore P ↔ Q. □                  │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  Important: the two directions can use DIFFERENT techniques.")
    print(f"  One might be direct, the other contrapositive.")
    print(f"  Don't assume the same argument works both ways.")
    print(f"")
    print(f"  Example: n is even ↔ n² is even.")
    print(f"")
    print(f"  PROOF:")
    print(f"  (→) Suppose n is even. Then n = 2k.")
    print(f"      n² = (2k)² = 4k² = 2(2k²). So n² is even. ✓")
    print(f"")
    print(f"  (←) We prove the contrapositive: n odd → n² odd.")
    print(f"      Suppose n is odd. Then n = 2k+1.")
    print(f"      n² = (2k+1)² = 4k²+4k+1 = 2(2k²+2k)+1. Odd. ✓")
    print(f"")
    print(f"  Therefore n is even ↔ n² is even. □")
    print(f"")
    print(f"  Notice:")
    print(f"  · (→) was proved directly.")
    print(f"  · (←) was proved by contrapositive.")
    print(f"  · Different techniques for different directions — perfectly fine.")


def proving_universals():
    print(f"\n{'='*50}")
    print(f"PROVING FOR ALL STATEMENTS  (∀x P(x))")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: ∀x P(x)")
    print(f"  Method: introduce an ARBITRARY x. Prove P(x).")
    print(f"  Because x was arbitrary, the proof works for any x.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Let x be an arbitrary [element].     │")
    print(f"  │ [prove P(x)]                         │")
    print(f"  │ Since x was arbitrary, ∀x P(x). □   │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  ARBITRARY means: no special assumptions about x.")
    print(f"  You can only use what's stated in the hypotheses.")
    print(f"  Nothing else about x is known.")
    print(f"")
    print(f"  COMMON MISTAKE: checking specific values.")
    print(f"  'P(1) is true, P(2) is true, P(3) is true...'")
    print(f"  This NEVER proves ∀x P(x).")
    print(f"  You need the general case — not examples.")
    print(f"")
    print(f"  Example:")
    print(f"  Theorem: ∀n∈ℤ, if n > 2 and n is prime then n is odd.")
    print(f"")
    print(f"  ANALYSIS:")
    print(f"  Let n be arbitrary. Assume n > 2 and n is prime.")
    print(f"  Goal: n is odd.")
    print(f"  Try contrapositive: n even → n ≤ 2 or n not prime.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Let n be an arbitrary integer.")
    print(f"  We prove the contrapositive: if n is even then n ≤ 2 or n is not prime.")
    print(f"  Suppose n is even. Then n = 2k for some integer k.")
    print(f"  If k = 1: n = 2 ≤ 2. ✓")
    print(f"  If k > 1: n = 2·k has factor 2 with 1 < 2 < n, so n is not prime. ✓")
    print(f"  If k ≤ 0: n ≤ 0 < 2. ✓")
    print(f"  In all cases, n ≤ 2 or n is not prime.")
    print(f"  By contrapositive, if n > 2 and n is prime then n is odd. □")


def proving_existentials():
    print(f"\n{'='*50}")
    print(f"PROVING THERE EXISTS STATEMENTS  (∃x P(x))")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: ∃x P(x)")
    print(f"  Method: exhibit a SPECIFIC x₀ and verify P(x₀) is true.")
    print(f"  One example is all you need.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Let x₀ = [specific value].           │")
    print(f"  │ Then P(x₀): [verification].          │")
    print(f"  │ Therefore ∃x P(x). □                 │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  Finding x₀ is the creative part. Verifying it is mechanical.")
    print(f"")
    print(f"  TWO STRATEGIES for finding x₀:")
    print(f"")
    print(f"  STRATEGY 1 — Work backward:")
    print(f"  What must x₀ satisfy? Solve P(x) = true for x.")
    print(f"  Do this in scratch work. Present x₀ in the final proof.")
    print(f"")
    print(f"  STRATEGY 2 — Try simple values:")
    print(f"  Try x = 0, 1, -1, 2, ... until one works.")
    print(f"")
    print(f"  Example:")
    print(f"  Theorem: ∃x∈ℝ such that x² - x - 1 = 0.")
    print(f"")
    print(f"  SCRATCH WORK:")
    print(f"  Solve x² - x - 1 = 0 with the quadratic formula.")
    print(f"  x = (1 ± √5)/2")
    print(f"  Take x₀ = (1+√5)/2.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Let x₀ = (1+√5)/2.")
    print(f"  Then x₀² = (6+2√5)/4 = (3+√5)/2.")
    print(f"  x₀² - x₀ - 1 = (3+√5)/2 - (1+√5)/2 - 1 = 2/2 - 1 = 0. ✓")
    print(f"  Therefore ∃x∈ℝ: x² - x - 1 = 0. □")
    print(f"")
    print(f"  --- DISPROVING existentials ---")
    print(f"  To show ∃x P(x) is FALSE:")
    print(f"  Prove ∀x ¬P(x) — that no x satisfies P.")
    print(f"  This requires a universal proof, which is usually harder.")


def proof_by_induction():
    print(f"\n{'='*50}")
    print(f"PROOF BY INDUCTION")
    print(f"{'='*50}")
    print(f"")
    print(f"  Goal: ∀n∈ℕ, P(n)  (P holds for all natural numbers)")
    print(f"")
    print(f"  Induction is the technique built specifically for this.")
    print(f"  Think of it as dominoes:")
    print(f"  · The first domino falls  (base case)")
    print(f"  · Each falling domino knocks over the next  (inductive step)")
    print(f"  · Therefore ALL dominoes fall")
    print(f"")
    print(f"  TWO STEPS:")
    print(f"")
    print(f"  BASE CASE: prove P(0) (or P(1), wherever you start).")
    print(f"  INDUCTIVE STEP: prove P(n) → P(n+1).")
    print(f"    Assume P(n) — this is the INDUCTIVE HYPOTHESIS.")
    print(f"    Use it to prove P(n+1).")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Base case: [prove P(0)]              │")
    print(f"  │ Inductive step:                      │")
    print(f"  │   Let n be arbitrary.                │")
    print(f"  │   Suppose P(n).  [inductive hyp.]    │")
    print(f"  │   [prove P(n+1) using P(n)]          │")
    print(f"  │ By induction, ∀n P(n). □             │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  --- EXAMPLE 1 ---")
    print(f"  Theorem: for all n ≥ 1, 1+2+...+n = n(n+1)/2.")
    print(f"")
    print(f"  Base case (n=1):")
    print(f"  Left: 1. Right: 1·2/2 = 1. ✓")
    print(f"")
    print(f"  Inductive step:")
    print(f"  Suppose 1+2+...+k = k(k+1)/2.  [inductive hypothesis]")
    print(f"  Then:")
    print(f"  1+2+...+k+(k+1) = k(k+1)/2 + (k+1)    [by IH]")
    print(f"                   = (k+1)[k/2 + 1]")
    print(f"                   = (k+1)(k+2)/2         ✓")
    print(f"")
    print(f"  By induction, the formula holds for all n ≥ 1. □")
    print(f"")
    print(f"  --- EXAMPLE 2 ---")
    print(f"  Theorem: for all n ≥ 0, 3 | (n³-n).")
    print(f"")
    print(f"  Base case (n=0): 0³-0 = 0 = 3·0. ✓")
    print(f"")
    print(f"  Inductive step:")
    print(f"  Suppose 3 | (k³-k).  [IH]")
    print(f"  (k+1)³-(k+1) = k³+3k²+3k+1-k-1")
    print(f"               = (k³-k) + 3k²+3k")
    print(f"               = (k³-k) + 3k(k+1)")
    print(f"  3 | (k³-k) by IH. 3 | 3k(k+1) obviously.")
    print(f"  Therefore 3 | (k+1)³-(k+1). ✓")
    print(f"")
    print(f"  By induction, 3 | (n³-n) for all n ≥ 0. □")

    print(f"\n  --- Verification ---")
    print(f"  {'n':>5}  {'n³-n':>8}  {'÷3':>6}  {'✓':>4}")
    print(f"  {'─'*28}")
    for n in range(8):
        val = n**3 - n
        print(f"  {n:>5}  {val:>8}  {val//3:>6}  {'✓' if val%3==0 else '✗':>4}")


def strong_induction():
    print(f"\n{'='*50}")
    print(f"STRONG INDUCTION")
    print(f"{'='*50}")
    print(f"")
    print(f"  Regular induction: to prove P(n+1), you may use P(n).")
    print(f"  Strong induction: to prove P(n+1), you may use")
    print(f"  P(0), P(1), P(2), ..., P(n) — ALL previous cases.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Base case: [prove P(0)]              │")
    print(f"  │ Inductive step:                      │")
    print(f"  │   Let n be arbitrary.                │")
    print(f"  │   Suppose P(k) for ALL k < n.        │")
    print(f"  │   [prove P(n) using any P(k), k<n]  │")
    print(f"  │ By strong induction, ∀n P(n). □      │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  Strong induction is NOT more powerful than regular induction.")
    print(f"  They prove the same theorems.")
    print(f"  But strong induction is more CONVENIENT when P(n)")
    print(f"  depends on values earlier than just P(n-1).")
    print(f"")
    print(f"  --- EXAMPLE: every integer n ≥ 2 is a product of primes ---")
    print(f"")
    print(f"  Why strong induction?")
    print(f"  To factor n = a·b, both a and b are less than n.")
    print(f"  But a could be far less than n-1 — not just one step back.")
    print(f"  We need ALL previous cases, not just the previous one.")
    print(f"")
    print(f"  PROOF:")
    print(f"  Base case (n=2): 2 is prime, so it is a product of primes. ✓")
    print(f"")
    print(f"  Inductive step:")
    print(f"  Let n ≥ 3. Suppose every integer k with 2 ≤ k < n")
    print(f"  is a product of primes.  [strong IH]")
    print(f"")
    print(f"  Case 1: n is prime.")
    print(f"    Then n itself is a product of one prime. ✓")
    print(f"")
    print(f"  Case 2: n is composite.")
    print(f"    Then n = a·b with 2 ≤ a,b < n.")
    print(f"    By the strong IH, a = p₁·...·pⱼ and b = q₁·...·qₖ.")
    print(f"    Therefore n = p₁·...·pⱼ·q₁·...·qₖ. ✓")
    print(f"")
    print(f"  By strong induction, every n ≥ 2 is a product of primes. □")
    print(f"")
    print(f"  This proves EXISTENCE in the Fundamental Theorem of Arithmetic.")
    print(f"  (Proving UNIQUENESS of the factorization requires more work.)")


def relations_and_functions():
    print(f"\n{'='*50}")
    print(f"RELATIONS AND FUNCTIONS")
    print(f"{'='*50}")
    print(f"")
    print(f"  Relations and functions are mathematical objects")
    print(f"  where proof techniques apply directly.")
    print(f"  Proving a relation is an equivalence, or a function")
    print(f"  is injective, means taking the definitions and")
    print(f"  applying the proof strategies from Part 3.")
    print(f"")
    print(f"  1 — Relations and equivalence relations")
    print(f"  2 — Functions: injective, surjective, bijective")
    print(f"  3 — Proving function properties")
    print(f"  4 — Composition and inverses")
    print(f"")
    choice = input("  Enter 1, 2, 3, or 4: ")

    if choice == "1":
        equivalence_relations()
    elif choice == "2":
        function_types()
    elif choice == "3":
        proving_function_properties()
    elif choice == "4":
        composition_inverses()
    else:
        print(f"  Invalid choice.")


def equivalence_relations():
    print(f"\n{'='*50}")
    print(f"RELATIONS AND EQUIVALENCE RELATIONS")
    print(f"{'='*50}")
    print(f"")
    print(f"  A relation on a set A is a rule that says,")
    print(f"  for each pair of elements, whether they are related or not.")
    print(f"  We write a ~ b or aRb to mean 'a is related to b'.")
    print(f"")
    print(f"  Examples of relations:")
    print(f"  · '≤' on ℝ:    a ≤ b means a is less than or equal to b")
    print(f"  · '|' on ℤ:    a | b means a divides b")
    print(f"  · '=' is also a relation — the strictest one")
    print(f"  · 'has the same birthday as' on a set of people")
    print(f"")
    print(f"  THREE PROPERTIES:")
    print(f"")
    print(f"  REFLEXIVE: every element is related to itself.")
    print(f"  ∀a, a ~ a")
    print(f"  '≤' is reflexive: a ≤ a always. ✓")
    print(f"  '<' is NOT reflexive: a < a is always false. ✗")
    print(f"")
    print(f"  SYMMETRIC: if a ~ b then b ~ a.")
    print(f"  '=' is symmetric. '≤' is NOT (5≤7 but 7≰5).")
    print(f"  'has the same birthday as' is symmetric. ✓")
    print(f"")
    print(f"  TRANSITIVE: if a~b and b~c then a~c.")
    print(f"  '≤' is transitive. ✓")
    print(f"  'is perpendicular to' is NOT transitive.")
    print(f"  (L₁⊥L₂ and L₂⊥L₃ means L₁ ∥ L₃ — not perpendicular!)")
    print(f"")
    print(f"  EQUIVALENCE RELATION = all three properties hold.")
    print(f"  An equivalence relation groups elements into")
    print(f"  EQUIVALENCE CLASSES — clusters of mutually related elements.")
    print(f"  'Has the same birthday' partitions people by birthday.")
    print(f"")
    print(f"  Classic example: congruence modulo n.")
    print(f"  a ≡ b (mod n)  means  n | (a-b)")
    print(f"")
    print(f"  PROOF that ≡ (mod n) is an equivalence relation:")
    print(f"")
    print(f"  Reflexive: a ≡ a (mod n)?")
    print(f"  Need: n | (a-a) = 0. Yes — n | 0 for any n. ✓")
    print(f"")
    print(f"  Symmetric: if a ≡ b (mod n), then b ≡ a (mod n)?")
    print(f"  Suppose n | (a-b). Then a-b = nk.")
    print(f"  So b-a = -nk = n(-k). Since -k∈ℤ, n | (b-a). ✓")
    print(f"")
    print(f"  Transitive: if a≡b and b≡c, then a≡c (mod n)?")
    print(f"  Suppose a-b = nj and b-c = nk.")
    print(f"  Then a-c = (a-b)+(b-c) = nj+nk = n(j+k). ✓")
    print(f"")
    print(f"  All three hold — ≡ (mod n) is an equivalence relation. □")
    print(f"")
    print(f"  HOW TO PROVE ANY RELATION IS AN EQUIVALENCE RELATION:")
    print(f"  Check all three properties.")
    print(f"  For each, state what you need to show,")
    print(f"  then prove it using the definition of the relation.")
    print(f"  Never skip a property — you need all three.")


def function_types():
    print(f"\n{'='*50}")
    print(f"FUNCTIONS: INJECTIVE, SURJECTIVE, BIJECTIVE")
    print(f"{'='*50}")
    print(f"")
    print(f"  A function f: A → B assigns to each element of A")
    print(f"  exactly one element of B.")
    print(f"  A is the domain, B is the codomain.")
    print(f"")
    print(f"  THREE IMPORTANT PROPERTIES:")
    print(f"")
    print(f"  INJECTIVE (one-to-one):")
    print(f"  Different inputs give different outputs.")
    print(f"  ∀a₁,a₂∈A: f(a₁) = f(a₂) → a₁ = a₂")
    print(f"  'No two arrows land on the same point.'")
    print(f"")
    print(f"  SURJECTIVE (onto):")
    print(f"  Every element of B is an output.")
    print(f"  ∀b∈B, ∃a∈A: f(a) = b")
    print(f"  'Every point in B gets hit by at least one arrow.'")
    print(f"")
    print(f"  BIJECTIVE:")
    print(f"  Injective AND surjective.")
    print(f"  'Every point in B gets hit by EXACTLY ONE arrow.'")
    print(f"  A bijection has an inverse function.")
    print(f"")
    print(f"  EXAMPLES:")
    print(f"  f: ℝ→ℝ, f(x) = 2x+1")
    print(f"  Injective? f(a)=f(b) → 2a+1=2b+1 → a=b. YES ✓")
    print(f"  Surjective? Given y, solve: x=(y-1)/2 ∈ ℝ. YES ✓")
    print(f"  Bijective? YES ✓")
    print(f"")
    print(f"  g: ℝ→ℝ, g(x) = x²")
    print(f"  Injective? g(2)=g(-2)=4 but 2≠-2. NO ✗")
    print(f"  Surjective? g(x)=-1 has no solution in ℝ. NO ✗")
    print(f"")
    print(f"  h: ℝ→[0,∞), h(x) = x²  (same formula, different codomain)")
    print(f"  Injective? Still NO.")
    print(f"  Surjective? Given y≥0, x=√y works. YES ✓")
    print(f"")
    print(f"  IMPORTANT: surjectivity depends on the codomain.")
    print(f"  Changing B changes whether f is surjective.")
    print(f"  Always check what B is declared to be.")


def proving_function_properties():
    print(f"\n{'='*50}")
    print(f"PROVING FUNCTION PROPERTIES")
    print(f"{'='*50}")
    print(f"")
    print(f"  HOW TO PROVE INJECTIVE:")
    print(f"  Goal: ∀a₁,a₂, f(a₁)=f(a₂) → a₁=a₂")
    print(f"  Form: universal + implication.")
    print(f"  Method: assume f(a₁)=f(a₂), derive a₁=a₂.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Suppose f(a₁) = f(a₂).              │")
    print(f"  │ [algebra]                            │")
    print(f"  │ Therefore a₁ = a₂.                  │")
    print(f"  │ So f is injective. □                 │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  HOW TO PROVE SURJECTIVE:")
    print(f"  Goal: ∀b∈B, ∃a∈A: f(a)=b")
    print(f"  Form: universal + existential.")
    print(f"  Method: let b be arbitrary, find a with f(a)=b.")
    print(f"  Scratch work: solve f(a)=b for a. Present solution in proof.")
    print(f"")
    print(f"  Template:")
    print(f"  ┌─────────────────────────────────────┐")
    print(f"  │ Let b∈B be arbitrary.               │")
    print(f"  │ Let a = [formula].                   │")
    print(f"  │ Then f(a) = [verify] = b. ✓          │")
    print(f"  │ So f is surjective. □                │")
    print(f"  └─────────────────────────────────────┘")
    print(f"")
    print(f"  HOW TO DISPROVE INJECTIVE:")
    print(f"  Find a₁ ≠ a₂ with f(a₁) = f(a₂). One example is enough.")
    print(f"")
    print(f"  HOW TO DISPROVE SURJECTIVE:")
    print(f"  Find b∈B such that f(a)≠b for all a. Show no preimage exists.")
    print(f"")
    print(f"  --- WORKED EXAMPLE ---")
    print(f"  Theorem: f: ℝ→ℝ, f(x) = 3x-5 is bijective.")
    print(f"")
    print(f"  INJECTIVE:")
    print(f"  Suppose f(x₁) = f(x₂).")
    print(f"  Then 3x₁-5 = 3x₂-5.")
    print(f"  Adding 5: 3x₁ = 3x₂.")
    print(f"  Dividing by 3: x₁ = x₂.")
    print(f"  So f is injective. □")
    print(f"")
    print(f"  SURJECTIVE:")
    print(f"  [Scratch: solve 3x-5=y → x=(y+5)/3]")
    print(f"  Let y∈ℝ be arbitrary.")
    print(f"  Let x = (y+5)/3. Then x∈ℝ and:")
    print(f"  f(x) = 3·(y+5)/3 - 5 = y+5-5 = y. ✓")
    print(f"  So f is surjective. □")
    print(f"")
    print(f"  Therefore f is bijective. □")
    print(f"")
    print(f"  Notice:")
    print(f"  · Injective: assume equal outputs → derive equal inputs.")
    print(f"  · Surjective: work backward to find x, then verify forward.")
    print(f"  · Both proofs follow directly from the definitions.")


def composition_inverses():
    print(f"\n{'='*50}")
    print(f"COMPOSITION AND INVERSES")
    print(f"{'='*50}")
    print(f"")
    print(f"  COMPOSITION:")
    print(f"  If f: A→B and g: B→C,")
    print(f"  then g∘f: A→C means 'apply f first, then g'.")
    print(f"  (g∘f)(a) = g(f(a))")
    print(f"")
    print(f"  Key theorems:")
    print(f"  · f and g both injective  → g∘f injective")
    print(f"  · f and g both surjective → g∘f surjective")
    print(f"  · g∘f injective  → f injective")
    print(f"  · g∘f surjective → g surjective")
    print(f"")
    print(f"  PROOF (f,g injective → g∘f injective):")
    print(f"  Suppose f and g are injective.")
    print(f"  Suppose (g∘f)(a₁) = (g∘f)(a₂).")
    print(f"  Then g(f(a₁)) = g(f(a₂)).")
    print(f"  Since g is injective: f(a₁) = f(a₂).")
    print(f"  Since f is injective: a₁ = a₂.")
    print(f"  Therefore g∘f is injective. □")
    print(f"")
    print(f"  INVERSE FUNCTIONS:")
    print(f"  f: A→B has an inverse iff f is bijective.")
    print(f"  The inverse f⁻¹: B→A satisfies:")
    print(f"  · f⁻¹(f(a)) = a  for all a∈A")
    print(f"  · f(f⁻¹(b)) = b  for all b∈B")
    print(f"")
    print(f"  To find f⁻¹: solve y = f(x) for x.")
    print(f"  To verify: check BOTH compositions.")
    print(f"")
    print(f"  Example: f(x) = 3x-5.")
    print(f"  Finding: y = 3x-5 → x = (y+5)/3")
    print(f"  So f⁻¹(x) = (x+5)/3.")
    print(f"")
    print(f"  Verifying:")
    print(f"  f⁻¹(f(x)) = f⁻¹(3x-5) = (3x-5+5)/3 = 3x/3 = x ✓")
    print(f"  f(f⁻¹(y)) = f((y+5)/3) = 3(y+5)/3-5 = y+5-5 = y ✓")
    print(f"  Therefore f⁻¹(x) = (x+5)/3. □")


def olympiad_problems():
    print(f"\n{'='*50}")
    print(f"OLYMPIAD PROBLEMS")
    print(f"{'='*50}")
    print(f"")
    print(f"  This is where everything comes together.")
    print(f"  Real problems, solved completely.")
    print(f"  Not just the answer — the strategy.")
    print(f"  How do you find the idea?")
    print(f"  Why that technique?")
    print(f"  Where would a beginner get stuck?")
    print(f"")
    print(f"  Each problem has four parts:")
    print(f"  1. The problem")
    print(f"  2. The analysis — how to find the approach")
    print(f"  3. The complete proof")
    print(f"  4. The reflection — what to remember")
    print(f"")
    print(f"  1 — Divisibility:  6 | n³-n  for all integers n")
    print(f"  2 — Infinite primes")
    print(f"  3 — Irrationality: √2 is irrational")
    print(f"  4 — Sum formula:   1²+2²+...+n² = n(n+1)(2n+1)/6")
    print(f"  5 — Pigeonhole:    among 5 integers, two share remainder mod 4")
    print(f"  6 — Pascal:        C(n,k) = C(n-1,k-1) + C(n-1,k)")
    print(f"  7 — Finite sets:   injective ↔ surjective on {{1,...,n}}")
    print(f"")
    choice = input("  Enter 1-7: ")

    if choice == "1":
        problem_divisibility()
    elif choice == "2":
        problem_infinite_primes()
    elif choice == "3":
        problem_sqrt2()
    elif choice == "4":
        problem_sum_squares()
    elif choice == "5":
        problem_pigeonhole()
    elif choice == "6":
        problem_pascal()
    elif choice == "7":
        problem_finite_injection()
    else:
        print(f"  Invalid choice.")


def problem_divisibility():
    print(f"\n{'='*50}")
    print(f"PROBLEM 1: PROVE THAT 6 | n³-n FOR ALL n∈ℤ")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  For every integer n, the number n³-n is divisible by 6.")
    print(f"")
    print(f"  --- STEP 1: Write GIVEN and GOAL ---")
    print(f"  GIVEN: n is an integer.")
    print(f"  GOAL:  6 | n³-n")
    print(f"  FORM:  universal → introduce arbitrary n.")
    print(f"")
    print(f"  --- STEP 2: Factor ---")
    print(f"  Before choosing a technique, try to SIMPLIFY the expression.")
    print(f"  n³-n = n(n²-1) = n(n-1)(n+1) = (n-1)·n·(n+1)")
    print(f"  This is the product of THREE CONSECUTIVE integers!")
    print(f"  That's the key insight.")
    print(f"")
    print(f"  --- STEP 3: Why does this help? ---")
    print(f"  Among any three consecutive integers:")
    print(f"  · At least one is divisible by 2  (every other integer is even)")
    print(f"  · Exactly one is divisible by 3   (every third integer is)")
    print(f"  So their product is divisible by both 2 and 3,")
    print(f"  hence by 6.")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  Let n be an arbitrary integer.")
    print(f"  Note that n³-n = (n-1)·n·(n+1),")
    print(f"  the product of three consecutive integers.")
    print(f"")
    print(f"  2 | (n-1)n(n+1):")
    print(f"  Among n-1 and n (two consecutive integers),")
    print(f"  one must be even. Therefore 2 | (n-1)n(n+1).")
    print(f"")
    print(f"  3 | (n-1)n(n+1):")
    print(f"  Every integer has remainder 0, 1, or 2 when divided by 3.")
    print(f"  Case 1: n ≡ 0 (mod 3). Then 3 | n.")
    print(f"  Case 2: n ≡ 1 (mod 3). Then n-1 ≡ 0, so 3 | (n-1).")
    print(f"  Case 3: n ≡ 2 (mod 3). Then n+1 ≡ 0, so 3 | (n+1).")
    print(f"  In all cases 3 | (n-1)n(n+1).")
    print(f"")
    print(f"  Since 2 | (n-1)n(n+1) and 3 | (n-1)n(n+1),")
    print(f"  and gcd(2,3) = 1, we conclude 6 | (n-1)n(n+1) = n³-n. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The key move was FACTORING n³-n before doing anything else.")
    print(f"  Once you see (n-1)n(n+1), the proof is obvious.")
    print(f"  Without the factoring, the problem seems hard.")
    print(f"  Lesson: always simplify the expression before choosing a technique.")

    print(f"\n  Verification:")
    print(f"  {'n':>5}  {'n³-n':>8}  {'÷6':>6}  {'✓':>4}")
    print(f"  {'─'*28}")
    for n in range(-4, 6):
        val = n**3 - n
        print(f"  {n:>5}  {val:>8}  {val//6:>6}  {'✓' if val%6==0 else '✗':>4}")


def problem_infinite_primes():
    print(f"\n{'='*50}")
    print(f"PROBLEM 2: THERE ARE INFINITELY MANY PRIMES")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  Prove that the set of prime numbers is infinite.")
    print(f"")
    print(f"  --- ANALYSIS ---")
    print(f"  GOAL: infinitely many primes.")
    print(f"  FORM: negation — we want to prove this is not finite.")
    print(f"  Strategy: proof by contradiction.")
    print(f"  Assume finitely many primes → we can list them all.")
    print(f"  From a finite list, can we derive a contradiction?")
    print(f"")
    print(f"  KEY IDEA: take ALL the primes, multiply them, add 1.")
    print(f"  N = p₁·p₂·...·pₙ + 1")
    print(f"  N is not divisible by any pᵢ — remainder is always 1.")
    print(f"  But N > 1, so N has some prime factor.")
    print(f"  That prime is not on our list — contradicting completeness.")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  Suppose for contradiction there are finitely many primes.")
    print(f"  List them all: p₁, p₂, ..., pₙ.")
    print(f"  Let N = p₁·p₂·...·pₙ + 1.")
    print(f"")
    print(f"  Since N > 1, N has at least one prime factor p.")
    print(f"  Since p₁,...,pₙ is a complete list, p = pᵢ for some i.")
    print(f"  Then pᵢ | N  and  pᵢ | p₁·p₂·...·pₙ.")
    print(f"  Therefore pᵢ | (N - p₁·p₂·...·pₙ) = 1.")
    print(f"  But no integer > 1 divides 1 — contradiction.")
    print(f"")
    print(f"  Therefore there are infinitely many primes. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  COMMON MISTAKE: thinking N must be prime.")
    print(f"  N is NOT necessarily prime — it can be composite.")
    print(f"  Example: 2·3·5·7·11·13 + 1 = 30031 = 59·509. Composite!")
    print(f"  The proof says N has a prime factor NOT on the list.")
    print(f"  It doesn't say N itself is that prime.")
    print(f"")
    print(f"  This proof is by Euclid, around 300 BC.")
    print(f"  One of the most beautiful proofs ever written.")

    print(f"\n  N for various prime lists:")
    primes = [2, 3, 5, 7, 11, 13]
    print(f"  {'Primes used':>25}  {'N':>10}  {'N prime?':>10}")
    print(f"  {'─'*50}")
    for i in range(1, 7):
        subset = primes[:i]
        product = 1
        for p in subset:
            product *= p
        N    = product + 1
        is_p = all(N % d != 0 for d in range(2, int(N**0.5)+1))
        print(f"  {str(subset):>25}  {N:>10}  {'Yes' if is_p else 'No':>10}")


def problem_sqrt2():
    print(f"\n{'='*50}")
    print(f"PROBLEM 3: √2 IS IRRATIONAL")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  Prove that √2 cannot be written as a fraction p/q")
    print(f"  with p and q integers.")
    print(f"")
    print(f"  --- ANALYSIS ---")
    print(f"  GOAL: √2 ∉ ℚ  (not rational)")
    print(f"  FORM: negation → proof by contradiction.")
    print(f"  Assume √2 IS rational. Get a contradiction.")
    print(f"")
    print(f"  If √2 = p/q, we can always reduce the fraction.")
    print(f"  So assume p/q is already in LOWEST TERMS: gcd(p,q)=1.")
    print(f"  This is the thing we'll contradict at the end.")
    print(f"")
    print(f"  Square both sides: 2q² = p²")
    print(f"  → p² even → p even → p=2k")
    print(f"  → q² = 2k² → q² even → q even")
    print(f"  → 2|p and 2|q → contradicts gcd(p,q)=1")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  Suppose for contradiction that √2 is rational.")
    print(f"  Write √2 = p/q where p,q∈ℤ, q≠0, and gcd(p,q)=1.")
    print(f"  (We can always reduce any fraction to lowest terms.)")
    print(f"")
    print(f"  Squaring: 2 = p²/q², so p² = 2q².")
    print(f"  Therefore p² is even.")
    print(f"  By the theorem 'n² even → n even': p is even.")
    print(f"  Write p = 2k for some integer k.")
    print(f"  Then (2k)² = 2q², so 4k² = 2q², so q² = 2k².")
    print(f"  Therefore q² is even, so q is even.")
    print(f"  But now 2|p and 2|q, which contradicts gcd(p,q)=1.")
    print(f"")
    print(f"  Therefore √2 is irrational. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The proof builds on a previous result: n² even → n even.")
    print(f"  In mathematics, proofs always build on earlier theorems.")
    print(f"  Recognizing which earlier results to use is a key skill.")
    print(f"")
    print(f"  GENERALIZATION: replace 2 with any prime p.")
    print(f"  The same argument proves √p is irrational for any prime p.")
    print(f"  Try it yourself — it's the same proof word for word.")
    print(f"")
    print(f"  This proof is over 2000 years old.")
    print(f"  It shocked the ancient Greeks, who believed all numbers")
    print(f"  were rational. The person who discovered it")
    print(f"  was allegedly thrown overboard for revealing the truth.")


def problem_sum_squares():
    print(f"\n{'='*50}")
    print(f"PROBLEM 4: 1²+2²+...+n² = n(n+1)(2n+1)/6")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  For all n ≥ 1:")
    print(f"  1² + 2² + 3² + ... + n² = n(n+1)(2n+1)/6")
    print(f"")
    print(f"  --- ANALYSIS ---")
    print(f"  GOAL: ∀n≥1, P(n) where P(n) is the formula.")
    print(f"  FORM: universal over natural numbers → induction.")
    print(f"")
    print(f"  The sum up to n+1 = (sum up to n) + (n+1)².")
    print(f"  This recursive structure is exactly what induction exploits.")
    print(f"")
    print(f"  Key algebraic step to verify:")
    print(f"  n(n+1)(2n+1)/6 + (n+1)² = (n+1)(n+2)(2n+3)/6")
    print(f"  Factor out (n+1)/6, then simplify.")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  We prove by induction on n.")
    print(f"")
    print(f"  Base case (n=1):")
    print(f"  Left side: 1² = 1.")
    print(f"  Right side: 1·2·3/6 = 6/6 = 1. ✓")
    print(f"")
    print(f"  Inductive step:")
    print(f"  Suppose 1²+...+k² = k(k+1)(2k+1)/6  for some k≥1. [IH]")
    print(f"  We show 1²+...+k²+(k+1)² = (k+1)(k+2)(2k+3)/6.")
    print(f"")
    print(f"  1²+...+k²+(k+1)²")
    print(f"  = k(k+1)(2k+1)/6 + (k+1)²              [by IH]")
    print(f"  = (k+1) · [k(2k+1)/6 + (k+1)]          [factor (k+1)]")
    print(f"  = (k+1) · [k(2k+1) + 6(k+1)] / 6       [common denominator]")
    print(f"  = (k+1) · [2k²+k+6k+6] / 6")
    print(f"  = (k+1) · [2k²+7k+6] / 6")
    print(f"  = (k+1)(k+2)(2k+3) / 6                  [factor 2k²+7k+6]")
    print(f"  = (k+1)((k+1)+1)(2(k+1)+1) / 6 ✓")
    print(f"")
    print(f"  By induction, the formula holds for all n ≥ 1. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The hard part is the algebra in the inductive step.")
    print(f"  Always factor out (k+1) first — it's the key move.")
    print(f"  Then verify 2k²+7k+6 = (k+2)(2k+3) by expanding.")
    print(f"")
    print(f"  Important: induction PROVES the formula but doesn't EXPLAIN")
    print(f"  where it came from. The formula was likely found by guessing")
    print(f"  and checking small cases first, then verified by induction.")

    print(f"\n  Verification:")
    print(f"  {'n':>4}  {'Sum':>8}  {'Formula':>10}  {'Match':>7}")
    print(f"  {'─'*34}")
    s = 0
    for n in range(1, 11):
        s += n**2
        f = n*(n+1)*(2*n+1)//6
        print(f"  {n:>4}  {s:>8}  {f:>10}  {'✓' if s==f else '✗':>7}")


def problem_pigeonhole():
    print(f"\n{'='*50}")
    print(f"PROBLEM 5: PIGEONHOLE PRINCIPLE")
    print(f"{'='*50}")
    print(f"")
    print(f"  THE PRINCIPLE:")
    print(f"  If you put n+1 objects into n boxes,")
    print(f"  at least one box contains at least 2 objects.")
    print(f"")
    print(f"  Proof of the principle:")
    print(f"  Suppose every box has at most 1 object.")
    print(f"  Then total objects ≤ n. But we have n+1. Contradiction. □")
    print(f"")
    print(f"  Simple. But enormously powerful.")
    print(f"  The skill is identifying what the 'objects' and 'boxes' are.")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  Among any 5 integers, two must have the same remainder mod 4.")
    print(f"")
    print(f"  --- ANALYSIS ---")
    print(f"  Objects: the 5 integers.")
    print(f"  Boxes: possible remainders mod 4 = {{0, 1, 2, 3}} — only 4 boxes.")
    print(f"  5 objects into 4 boxes → at least one box has 2 objects.")
    print(f"  Two integers in the same box = same remainder mod 4.")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  Let a₁, a₂, a₃, a₄, a₅ be any five integers.")
    print(f"  Each has a remainder when divided by 4: either 0, 1, 2, or 3.")
    print(f"  There are 5 integers but only 4 possible remainders.")
    print(f"  By the Pigeonhole Principle, at least two integers")
    print(f"  must have the same remainder mod 4. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The proof is three sentences.")
    print(f"  The work was in setting up the boxes correctly.")
    print(f"  Once you identify objects and boxes, it writes itself.")
    print(f"")
    print(f"  The harder skill: recognizing when pigeonhole applies.")
    print(f"  Whenever you see 'among n+1 things, two must share a property',")
    print(f"  think: what are the boxes?")
    print(f"")
    print(f"  Another example:")
    print(f"  'In any group of 13 people, two share a birth month.'")
    print(f"  Objects: 13 people. Boxes: 12 months.")
    print(f"  13 > 12 → pigeonhole. □")


def problem_pascal():
    print(f"\n{'='*50}")
    print(f"PROBLEM 6: PASCAL'S IDENTITY")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  For all n ≥ 1 and 1 ≤ k ≤ n:")
    print(f"  C(n,k) = C(n-1,k-1) + C(n-1,k)")
    print(f"")
    print(f"  This is the rule behind Pascal's triangle.")
    print(f"  Each entry = sum of the two directly above it.")
    print(f"")
    print(f"  --- ANALYSIS: TWO APPROACHES ---")
    print(f"")
    print(f"  APPROACH 1 — Algebra:")
    print(f"  Expand C(n,k) = n!/(k!(n-k)!) and verify.")
    print(f"  Mechanical but gives no insight.")
    print(f"")
    print(f"  APPROACH 2 — Double counting (better):")
    print(f"  C(n,k) counts k-element subsets of {{1,...,n}}.")
    print(f"  Focus on whether element n is in the subset or not.")
    print(f"  Case 1: n is in → choose k-1 from {{1,...,n-1}} → C(n-1,k-1)")
    print(f"  Case 2: n is out → choose k from {{1,...,n-1}} → C(n-1,k)")
    print(f"  Total: C(n,k) = C(n-1,k-1) + C(n-1,k). □")
    print(f"")
    print(f"  Double counting = counting the same set two different ways.")
    print(f"  One count gives the left side, the other gives the right.")
    print(f"  They must be equal. Elegant and completely rigorous.")
    print(f"")
    print(f"  --- THE PROOF (combinatorial) ---")
    print(f"")
    print(f"  We count k-element subsets of {{1,...,n}}.")
    print(f"  The total count is C(n,k) by definition.")
    print(f"")
    print(f"  Split by whether n is included:")
    print(f"  · Subsets containing n: need k-1 more from {{1,...,n-1}}.")
    print(f"    Count: C(n-1, k-1).")
    print(f"  · Subsets not containing n: need k from {{1,...,n-1}}.")
    print(f"    Count: C(n-1, k).")
    print(f"")
    print(f"  These cases are mutually exclusive and exhaustive.")
    print(f"  Therefore C(n,k) = C(n-1,k-1) + C(n-1,k). □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The combinatorial proof is shorter AND more insightful.")
    print(f"  It explains WHY the identity is true.")
    print(f"  When you have a combinatorial identity, always ask:")
    print(f"  'Can I count the same thing two different ways?'")
    print(f"  This technique — double counting — is one of the most")
    print(f"  powerful tools in discrete mathematics.")

    import math
    print(f"\n  Verification:")
    print(f"  {'n':>4}  {'k':>4}  {'C(n,k)':>8}  {'C(n-1,k-1)+C(n-1,k)':>22}  {'✓':>4}")
    print(f"  {'─'*48}")
    for n in range(2, 7):
        for k in range(1, n+1):
            lhs = math.comb(n, k)
            rhs = math.comb(n-1, k-1) + math.comb(n-1, k)
            print(f"  {n:>4}  {k:>4}  {lhs:>8}  {rhs:>22}  {'✓' if lhs==rhs else '✗':>4}")


def problem_finite_injection():
    print(f"\n{'='*50}")
    print(f"PROBLEM 7: INJECTIVE ↔ SURJECTIVE ON FINITE SETS")
    print(f"{'='*50}")
    print(f"")
    print(f"  STATEMENT:")
    print(f"  Let f: {{1,...,n}} → {{1,...,n}}.")
    print(f"  Prove: f is injective if and only if f is surjective.")
    print(f"")
    print(f"  On INFINITE sets this is FALSE.")
    print(f"  f: ℕ→ℕ, f(n)=n+1 is injective but NOT surjective (1 is never an output).")
    print(f"  The finiteness is essential.")
    print(f"")
    print(f"  --- ANALYSIS ---")
    print(f"  GOAL: injective ↔ surjective.")
    print(f"  FORM: biconditional → prove both directions.")
    print(f"")
    print(f"  (→): injective → surjective")
    print(f"  If f is injective, the n inputs produce n DISTINCT outputs.")
    print(f"  n distinct elements from an n-element set = the whole set.")
    print(f"  So every element of {{1,...,n}} is an output → surjective.")
    print(f"")
    print(f"  (←): surjective → injective")
    print(f"  If f is surjective, every output is hit at least once.")
    print(f"  n outputs, n inputs. If any output were hit twice,")
    print(f"  some other output would be hit zero times → not surjective.")
    print(f"  Contradiction. So every output is hit exactly once → injective.")
    print(f"")
    print(f"  --- THE PROOF ---")
    print(f"")
    print(f"  (→) Suppose f is injective.")
    print(f"  Since f: {{1,...,n}} → {{1,...,n}} is injective,")
    print(f"  f(1), f(2), ..., f(n) are n distinct elements of {{1,...,n}}.")
    print(f"  But {{1,...,n}} has exactly n elements.")
    print(f"  So {{f(1),...,f(n)}} = {{1,...,n}}.")
    print(f"  Every element of {{1,...,n}} is in the range of f.")
    print(f"  Therefore f is surjective. □")
    print(f"")
    print(f"  (←) Suppose f is surjective.")
    print(f"  Suppose for contradiction that f is NOT injective.")
    print(f"  Then f(i) = f(j) for some i ≠ j.")
    print(f"  The range of f has at most n-1 distinct values")
    print(f"  (since two inputs share one output).")
    print(f"  Therefore |range(f)| ≤ n-1 < n = |{{1,...,n}}|.")
    print(f"  So f is not surjective — contradiction.")
    print(f"  Therefore f is injective. □")
    print(f"")
    print(f"  --- REFLECTION ---")
    print(f"  The key: on a finite set, n distinct things from an n-element")
    print(f"  set fills the entire set. This is obvious but powerful.")
    print(f"  On infinite sets, 'infinite distinct things from an infinite set'")
    print(f"  does NOT fill the whole set — that's what makes them different.")
    print(f"  Hilbert's hotel shows this beautifully.")


def mathematical_proofs():
    print(f"\n{'='*50}")
    print(f"MATHEMATICAL PROOFS")
    print(f"{'='*50}")
    print(f"")
    print(f"  A mathematical proof is an argument that convinces")
    print(f"  any reader, beyond any doubt, that a statement is true.")
    print(f"  Not because it looks right. Not because we checked examples.")
    print(f"  Because the logic is airtight.")
    print(f"")
    print(f"  Most students think proofs require special talent or intuition.")
    print(f"  Velleman's 'How to Prove It' shows that's wrong.")
    print(f"  Proofs have STRUCTURE. The structure can be learned.")
    print(f"  Once you recognize the logical form of a statement,")
    print(f"  the proof strategy follows automatically.")
    print(f"")
    print(f"  You don't need to be brilliant — you need to read carefully.")
    print(f"")
    print(f"  This module covers everything in Velleman's book:")
    print(f"  from the first proposition to olympiad-level problems.")
    print(f"  Work through it in order — each part builds on the previous.")
    print(f"")
    print(f"  1 — Logic and language")
    print(f"       propositions, connectives, truth tables, quantifiers")
    print(f"  2 — Proof structure")
    print(f"       givens and goal, Velleman's method, forward and backward")
    print(f"  3 — Proof techniques")
    print(f"       direct, contrapositive, contradiction, induction, ...")
    print(f"  4 — Relations and functions")
    print(f"       equivalence, injective, surjective, inverse")
    print(f"  5 — Olympiad problems")
    print(f"       real problems solved with full strategy explained")
    print(f"")
    choice = input("  Enter 1, 2, 3, 4, or 5: ")

    if choice == "1":
        logic_and_language()
    elif choice == "2":
        proof_structure()
    elif choice == "3":
        proof_techniques()
    elif choice == "4":
        relations_and_functions()
    elif choice == "5":
        olympiad_problems()
    else:
        print(f"  Invalid choice. Please enter 1 to 5.")


if __name__ == "__main__":
    mathematical_proofs()
    